# Model Creation Pipeline Configuration
# This config file contains parameters for creating embedding models and vector databases

pipeline:
  name: "model_creation_pipeline"
  version: "1.0.0"
  description: "Creates embedding models and vector databases for RAG system"

# API configuration
api:
  API_key_string: "OPENAI_API_KEY"  # Environment variable name

model:
  LLM_model_name: "gpt-4.1"
  LLM_vendor_name: "openai"

dataset_generation:
  num_top_topics_for_questions: 5 # number of top topics to use for questions
  num_random_topics_for_questions: 5 # number of random topics to use for questions
  num_questions_per_topic: 2  # number of questions to generate for each topic
  topic_confidence_threshold: 0.5 # should be between 0 and 1; see "Probability" column in BERTopic output for more info

# MLflow tracking parameters
mlflow:
  experiment_name: "science_assist_model_creation"
  tracking_uri: "file:./mlruns"
  log_artifacts: true
  log_metrics:
    - "embedding_dimension"
    - "total_embeddings"
    - "index_size"
    - "creation_time"
    - "model_size_mb"
  log_parameters:
    - "embedding_model_name"
    - "index_type"
    - "batch_size"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/model_creation.log"

